### ISSUE TITLE
Switches Not working 

### ISSUE THREAD

**Issue by schirner** [neu-ece-esl/zpanel#1]
Students report that the switch input is not working:

https://github.com/orgs/neu-ece-4534-sp23/discussions/9

Can you please look into it?

**Comment by brunosmmm** [comment]
I can't access that link.

**Comment by schirner** [comment]
Sorry. I added you as a collaborator on the underlying discussion repository. Now it should work.

**Comment by brunosmmm** [comment]
Tried a couple of things in QEMU source, the event from the web client side reaches where it should, i.e. it tries to correctly write a MMR for the correct gpio chip, but that has no side effects. Reading that memory location immediately after shows no change.

I need to run QEMU under gdb for more information.

**Comment by schirner** [comment]
Awesome. 

Incidentally Qucheng Jiang <jiang.qu@northeastern.edu> also looks into this as he is using QEMU as part of my 4534 course and will play with the QEMU source code as well. He will implement (as continuation from 7368):

https://github.com/neu-ece-7368/qemu-xlnx/issues/1

He told me on the way back from class that he looked into the switches problem.  He said he found a missing return value in QEMU source code of the switches. So maybe we can delegate this work. I'll leave it up to you whichever is more efficient for you.

**Comment by brunosmmm** [comment]
The problem was in QEMU source, not zpanel
